apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicio-usuarios
  template:
    metadata:
      labels:
        app: servicio-usuarios
    spec:
      containers:
        - name: servicio-usuarios
          image: 975050047110.dkr.ecr.us-east-2.amazonaws.com/comedor-i:servicio-usuarios-api
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-usuarios
spec:
  type: LoadBalancer
  selector:
    app: servicio-usuarios
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
